package com.infernalgames;


import static com.codename1.ui.CN.*;

import com.codename1.ui.*;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;

import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.infernalgames.gui.*;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }

        //new StreamsListBack().show();
        //new BackGameList().show();
        new FrontGameList().show();
    }



    public void front(){
        Form frontSide= new Form();
        frontSide.setTitle("Infernal Games");
        frontSide.getToolbar().addCommandToSideMenu("Games", null, e-> new FrontGameList().show());
        frontSide.getToolbar().addCommandToSideMenu("Games", null, e-> new StreamsListFront().show());
        frontSide.add(new NewsletterList());
        frontSide.show();
    }

    public void back(){
        Form backSide= new Form();
        backSide.setTitle("Infernal Games");
        backSide.getToolbar().addMaterialCommandToSideMenu("Games", FontImage.MATERIAL_GAMES, e-> new BackGameList().show());
        backSide.getToolbar().addMaterialCommandToSideMenu("Streams", FontImage.MATERIAL_STREAM, e-> new StreamsListBack().show());
        backSide.getToolbar().addMaterialCommandToSideMenu("Newsletters", FontImage.MATERIAL_EMAIL, e-> new NewsletterList().show());
        backSide.add(new NewsletterList());
        backSide.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
